# Create a topic
POST http://localhost:8080/kafka/create-topic?
    name=test&
    partitions=3&
    replicationFactor=1

###
# Create simple message in the topic 'test'
POST http://localhost:8080/api/produce/text?
    topic=test&
    key={{$random.alphanumeric(8)}}&
    message={{$random.alphanumeric(8)}}
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###
# Call from docker
POST http://localhost:8180/kafka/create-topic?
    name=test&
    partitions=3&
    replicationFactor=1

###
# Create simple message in the topic 'test'
POST http://localhost:8180/api/produce/text?
    topic=test&
    key={{$random.alphanumeric(8)}}&
    message={{$random.alphanumeric(8)}}
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###
# Call from docker
POST http://localhost:8180/kafka/create-topic?
    name=text-topic&
    partitions=3&
    replicationFactor=2

###
POST http://localhost:8180/kafka/create-topic?
    name=user-events&
    partitions=3&
    replicationFactor=2

###
# Create simple message in the topic 'text-topic'
POST http://localhost:8180/api/produce/text?
    topic=text-topic&
    key={{$random.alphanumeric(8)}}&
    message={{$random.alphanumeric(8)}}
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###
# Create simple message in the topic 'user-events'
POST http://localhost:8180/api/produce/json?
    topic=user-events&
    key={{$random.alphanumeric(8)}}&
    message={{$random.alphanumeric(8)}}
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
Content-Type: application/json

{
  "id": {{$random.integer(4)}},
  "name": "message={{$random.alphanumeric(8)}}",
  "timestamp": {{$timestamp}}
}
