# Create a topic
POST http://localhost:8081/kafka/create-topic?
    name=test&
    partitions=3&
    replicationFactor=1

###
# Create simple message in the topic 'topic'
POST http://localhost:8081/api/produce?
    topic=test&
    message={{$random.alphanumeric(8)}}
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 0